[package]
name = "botstone"
version = "0.1.0"
authors = ["Professor Bloodstone <prof.bloodstone+git@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.6"
dotenv = "0.15.0"
log = "0.4"
unic-emoji-char = "0.9.0"
maplit = "1.0.2"
hex = "0.4"
once_cell = "1.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros", "signal"] }

[dependencies.serenity]
version = "0.9.0-rc.1"
default-features = true
features = ["collector", "rustls_backend"]

[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = ["runtime-tokio", "macros", "postgres", "migrate", "offline"]

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.7"
